config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  root 'reports#index'

  ### ADMIN ###
  namespace :admin do
    get 'dashboard',    to: 'static_pages#dashboard'
    get 'users',        to: 'static_pages#users'
    get 'communities',  to: 'static_pages#communities'
  end

  ### COMMUNITY_ADMIN ###
  namespace :community_admin do
    get 'dashboard',      to: 'static_pages#dashboard'
    get 'reports',        to: 'static_pages#reports'
    get 'users',          to: 'static_pages#users'
    get 'location_news',  to: 'static_pages#location_news'
  end

  ### COMMUNITIES ###
  resources :communities, only: [:index, :show, :update] do
    get :news, on: :member
    get :community_list, on: :collection
  end

  ### COMMUNITY SUBSCRIPTIONS ###
  resources :community_subscriptions, only: [:create, :destroy] do
    get :delete, on: :member
  end

  ### DELIVERIES ###
  resources :deliveries, only: [:new, :create] do
    get :deliver, on: :member
  end

  ### NEWSLETTERS ###
  resources :newsletters, except: [:edit, :update, :destroy]

  ### REPORTS ###
  resources :reports do
    member do
      get :report_index
      get :info_window
      get :delete
    end
    get :markers, on: :collection
  end

  ### SIDEKIQ ####
  authenticate :user, -> (u) { u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  ### USERS ###
  devise_for :users, controllers: { sessions: 'users/sessions',
                                    registrations: 'users/registrations',
                                    confirmations: 'users/confirmations' }

  resources :users, only: [:index] do
    get :notifications, on: :collection
    get :reports, on: :collection
    get :profile, on: :collection
  end

  post 'users/generate_user', to: 'users#generate_user'
  get 'users/new_admin_user', to: 'users#new_admin_user'
  post 'users/generate_community_admin_user', to: 'users#generate_community_admin_user'
  get 'users/new_community_admin_user', to: 'users#new_community_admin_user'

  ### NOTIFICATIONS ###
  resources :notifications, only: [:destroy]
  post 'notifications/read', to: 'notifications#read'

  ### USER_CATEGORIES ###
  resources :user_categories, only: :create

  ### ZIPCODES ###
  get 'search_streets', to: 'zipcodes#search_streets', as: 'search_streets'
  get 'search_towns', to: 'zipcodes#search_towns', as: 'search_towns'

  ### WRONG WORDS ###
  resources :wrong_words, only: [:index, :create, :destroy]

  ### CATEGORIES ###
  resources :categories, except: [:show]
end

app/views/shared/_dashboard_menu.html.erb
<div class='dashboard-menu-bg'>
  <div class='dashboard-menu'>
    <ul>
      <% if current_user.admin? %>
        <%= render 'admin/static_pages/admin_menu' %>
      <% elsif current_user.community? %>
        <%= render 'community_admin/static_pages/community_admin_menu' %>
      <% end %>
      <li class='<%= current_page_class(reports_users_path) %>'>
        <%= link_to 'Mijn meldingen', reports_users_path %>
      </li>
      <li class='<%= current_page_class(notifications_users_path) %>'>
        <%= link_to "Berichten ( #{notifications_count(current_user.id)} )", notifications_users_path %>
      </li>
      <li class='<%= current_page_class(profile_users_path) %>'>
        <%= link_to 'Profiel', profile_users_path %>
      </li>
      <% if current_user.community? %>
        <li>
          <%= link_to 'Mijn nieuws' %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/shared/_delete.html.erb
<h4><%= title %></h4>
<p><%= text %></p>
<% if controller_name == 'community_subscriptions' %>
  <a data-method="delete" class="modal-confirm button" href="/<%= controller_route %>/<%= el.id %>">Ja</a>
<% else %>
  <a data-method="delete" data-remote='true' data-id="<%= el.id %>"
                          data-controller-name="<%= controller_route %>"
                          class="modal-confirm button"
                          href="/<%= controller_route %>/<%= el.id %>">
    Ja
  </a>
<% end %>
<a href="#" class="modal-confirm button">Nee</a>'

app/views/shared/_footer.html.erb
<div class='footer'>
  <div class='container'>
    <div class='row'>
      <div class='columns four'>
        <h3>Adres</h3>
        <ul class='adres'>
          <li>
            IkBenInwoner
          </li>
          <li>
            Polle 11
          </li>
          <li>
            Rotsterhaule
          </li>
        </ul>
      </div>
      <div class='columns four'>
        <h3>Contact</h3>
        <ul class='contact'>
          <li>
            <i class="fa fa-mobile"></i> 06 542 473 43
          </li>
          <li>
            <i class="fa fa-phone"></i> (0513) 12 34 56
          </li>
          <li>
            <i class="fa fa-globe"></i> <%= link_to 'www.ikbeninwoner.nl', root_path, data: { no_turbolink: true }%>
          </li>
        </ul>
      </div>
      <div class='columns four'>
        <h3>Social</h3>
        <div class='social'>
          <i class="fa fa-twitter"></i>
          <i class="fa fa-facebook"></i>
        </div>
        <%= link_to 'Contact', root_path, data: { no_turbolink: true }, class: 'button' %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_modal.html.erb
<div class="modal">
  <div class='modal-header'>
    <div class='modal-close' title='Sluiten'></div>
  </div>
  <div class="modal-content"></div>
  <div class='modal-footer'></div>
</div>

app/views/shared/_side_menu.html.erb
<div class='side-menu'>
  <h4>Navigatie</h4>
  <ul>
    <% if user_signed_in? %>
    <li class='show-on-mobile'>
      <%= link_to 'Uitloggen', destroy_user_session_path, method: 'delete', class: 'pull-right' %>
    </li>
    <li class='show-on-mobile'>
      <%= link_to 'Profiel', user_path(current_user), data: { no_turbolink: true } %>
    </li>
    <% else %>
    <li class='show-on-mobile'>
      <%= link_to 'Inloggen', new_user_session_path, remote: true, class: 'js_modal' %>
    </li>
    <li class='show-on-mobile'>
      <%= link_to "Aanmelden", new_user_registration_path, remote: true, class: 'js_modal' %>
    </li>
    <% end %>
    <li>
      <%= link_to 'Gemeentes', communities_path, class: 'js_modal', remote: true %>
    </li>
    <% if current_user && current_user.admin? %>
      <li>
        <%= link_to 'Gebruikers', users_path %>
      </li>
    <% end %>
  </ul>
</div>

app/views/shared/_tutorial.html.erb
<div class='tutorial'>
  <p class='tut-left'><i class='fa fa-arrow-left'></i> Zoeken op locatie</p>
  <p class='tut-left'><i class='fa fa-arrow-left fa-6x'></i> Lijst van meldingen</p>
  <p class='tut-right'><i class='fa fa-arrow-up fa-6x'></i> Melding doen</p>
  <p class='tut-right2'><i class='fa fa-arrow-up fa-6x'></i> Nieuws</p>
  <h1>Welkom bij IkBenInwoner</h1>
  <h2>Verbeter je buurt door meldingen te doen over de openbare ruimte</h2>
  <h2>Blijf op de hoogte van locatiegericht nieuws</h2>>
</div>