config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  root 'reports#index'

  ### ADMIN ###
  namespace :admin do
    get 'dashboard',    to: 'static_pages#dashboard'
    get 'users',        to: 'static_pages#users'
    get 'communities',  to: 'static_pages#communities'
  end

  ### COMMUNITY_ADMIN ###
  namespace :community_admin do
    get 'dashboard',      to: 'static_pages#dashboard'
    get 'reports',        to: 'static_pages#reports'
    get 'users',          to: 'static_pages#users'
    get 'location_news',  to: 'static_pages#location_news'
  end

  ### COMMUNITIES ###
  resources :communities, only: [:index, :show, :update] do
    get :news, on: :member
    get :community_list, on: :collection
  end

  ### COMMUNITY SUBSCRIPTIONS ###
  resources :community_subscriptions, only: [:create, :destroy] do
    get :delete, on: :member
  end

  ### DELIVERIES ###
  resources :deliveries, only: [:new, :create] do
    get :deliver, on: :member
  end

  ### NEWSLETTERS ###
  resources :newsletters, except: [:edit, :update, :destroy]

  ### REPORTS ###
  resources :reports do
    member do
      get :report_index
      get :info_window
      get :delete
    end
    get :markers, on: :collection
  end

  ### SIDEKIQ ####
  authenticate :user, -> (u) { u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  ### USERS ###
  devise_for :users, controllers: { sessions: 'users/sessions',
                                    registrations: 'users/registrations',
                                    confirmations: 'users/confirmations' }

  resources :users, only: [:index] do
    get :notifications, on: :collection
    get :reports, on: :collection
    get :profile, on: :collection
  end

  post 'users/generate_user', to: 'users#generate_user'
  get 'users/new_admin_user', to: 'users#new_admin_user'
  post 'users/generate_community_admin_user', to: 'users#generate_community_admin_user'
  get 'users/new_community_admin_user', to: 'users#new_community_admin_user'

  ### NOTIFICATIONS ###
  resources :notifications, only: [:destroy]
  post 'notifications/read', to: 'notifications#read'

  ### USER_CATEGORIES ###
  resources :user_categories, only: :create

  ### ZIPCODES ###
  get 'search_streets', to: 'zipcodes#search_streets', as: 'search_streets'
  get 'search_towns', to: 'zipcodes#search_towns', as: 'search_towns'

  ### WRONG WORDS ###
  resources :wrong_words, only: [:index, :create, :destroy]

  ### CATEGORIES ###
  resources :categories, except: [:show]
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :user_categories
  has_many :users, through: :user_categories
  has_many :report_categories
  has_many :reports, through: :report_categories

  ### VALIDATIONS ###
  validates :title, presence: true
  validates :icon_name, presence: true
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :authenticate_admin!
  before_action :set_category, only: [:edit, :update, :destroy]

  def index
    @categories = Category.all
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      redirect_to categories_path, notice: "De categorie #{@category.title} is aangemaakt"
    else
      redirect_to categories_path, alert: 'De categorie kon niet worden opgeslagen'
    end
  end

  def edit
  end

  def update
    if @category.update(category_params)
      redirect_to categories_path, notice: "De categorie #{@category.title} is aangepast"
    else
      render 'edit', alert: 'De categorie kon niet worden opgeslagen'
    end
  end

  def destroy
    redirect_to categories_path, notice: "De categorie #{@category.title} is verwijdert" if @category.destroy
  end

  private

  def set_category
    @category = Category.find(params[:id])
  end

  def category_params
    params.require(:category).permit(:title, :icon_name)
  end
end

app/views/categories/_form.html.erb
<%= f.text_field :title, placeholder: 'Naam van de categorie', validate: '', class: 'u-full-width' %>
<i><small>
  De class namen voor een icon kunnen worden terug gevonden op:
  <a target='_blank' href='https://fortawesome.github.io/Font-Awesome/icons/'>Fontawsome</a>
</small></i>
<%= f.text_field :icon_name, placeholder: 'Fontawsome icon class naam', validate: '', class: 'u-full-width' %>

app/views/categories/_new.html.erb
<div class='panel-header'>
  <h5>Categorie toevoegen</h5>
  <i><small>Hier kunt u nieuwe categorieën toevoegen aan de applicatie</small></i>
</div>
<div class='panel-body'>
  <%= form_for category do |f| %>
    <%= render 'form', f: f %>
    <%= f.submit 'Categorie toevoegen' %>
  <% end %>
</div>

app/views/categories/edit.html.erb
<%= render 'shared/dashboard_menu' %>

<div class='inner'>
  <div class='container'>
    <div class='row'>
      <div class='columns three'>
        <%= render 'users/panels/user_image_panel', user: current_user %>
        <%= render 'users/panels/user_info_panel', user: current_user %>
      </div>
      <div class='columns nine'>
        <div class='panel'>
          <div class='panel-header'>
            <h5>Categorie aanpassen</h5>
          </div>
          <div class='panel-body'>
            <%= form_for @category do |f| %>
              <%= render 'form', f: f %>
              <%= f.submit 'Categorie aanpasen' %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/categories/index.html.erb
<%= render 'shared/dashboard_menu' %>

<div class='inner'>
  <div class='container'>
    <div class='row'>
      <div class='columns three'>
        <%= render 'users/panels/user_image_panel', user: current_user %>
        <%= render 'users/panels/user_info_panel', user: current_user %>
      </div>
      <div class='columns nine'>
        <div class='panel'>
          <%= render 'new', category: @category %>
        </div>
        <div class='panel'>
          <div class='panel-header'>
            <h5>Alle categorieën</h5>
          </div>
          <div class='panel-body'>
            <div class='row'>
              <div class='columns five'>
                <strong>Categorie beschrijving:</strong>
              </div>
              <div class='columns three'>
                <strong>Icon naam:</strong>
              </div>
            </div>
            <% @categories.each do |category| %>
              <div class='row'>
                <div class='columns five'>
                  <%= category.title %>
                </div>
                <div class='columns three'>
                  <%= category.icon_name %>
                </div>
                <div class='columns four'>
                  <%= link_to 'Aanpassen', edit_category_path(category) %> |
                  <%= link_to 'Verwijderen?',  category, method: :delete,
                                                         data: {confirm: 'Weet je het zeker'} %>
                </div>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>