config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  root 'reports#index'

  ### ADMIN ###
  namespace :admin do
    get 'dashboard',    to: 'static_pages#dashboard'
    get 'users',        to: 'static_pages#users'
    get 'communities',  to: 'static_pages#communities'
  end

  ### COMMUNITY_ADMIN ###
  namespace :community_admin do
    get 'dashboard',      to: 'static_pages#dashboard'
    get 'reports',        to: 'static_pages#reports'
    get 'users',          to: 'static_pages#users'
    get 'location_news',  to: 'static_pages#location_news'
  end

  ### COMMUNITIES ###
  resources :communities, only: [:index, :show, :update] do
    get :news, on: :member
    get :community_list, on: :collection
  end

  ### COMMUNITY SUBSCRIPTIONS ###
  resources :community_subscriptions, only: [:create, :destroy] do
    get :delete, on: :member
  end

  ### DELIVERIES ###
  resources :deliveries, only: [:new, :create] do
    get :deliver, on: :member
  end

  ### NEWSLETTERS ###
  resources :newsletters, except: [:edit, :update, :destroy]

  ### REPORTS ###
  resources :reports do
    member do
      get :report_index
      get :info_window
      get :delete
    end
    get :markers, on: :collection
  end

  ### SIDEKIQ ####
  authenticate :user, -> (u) { u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  ### USERS ###
  devise_for :users, controllers: { sessions: 'users/sessions',
                                    registrations: 'users/registrations',
                                    confirmations: 'users/confirmations' }

  resources :users, only: [:index] do
    get :notifications, on: :collection
    get :reports, on: :collection
    get :profile, on: :collection
  end

  post 'users/generate_user', to: 'users#generate_user'
  get 'users/new_admin_user', to: 'users#new_admin_user'
  post 'users/generate_community_admin_user', to: 'users#generate_community_admin_user'
  get 'users/new_community_admin_user', to: 'users#new_community_admin_user'

  ### NOTIFICATIONS ###
  resources :notifications, only: [:destroy]
  post 'notifications/read', to: 'notifications#read'

  ### USER_CATEGORIES ###
  resources :user_categories, only: :create

  ### ZIPCODES ###
  get 'search_streets', to: 'zipcodes#search_streets', as: 'search_streets'
  get 'search_towns', to: 'zipcodes#search_towns', as: 'search_towns'

  ### WRONG WORDS ###
  resources :wrong_words, only: [:index, :create, :destroy]

  ### CATEGORIES ###
  resources :categories, except: [:show]
end

app/controllers/admin/static_pages_controller.rb
module Admin
  class StaticPagesController < ApplicationController
    before_action :authenticate_admin!

    def dashboard
    end

    def users
      @users = User.paginate(page: params[:page], per_page: 20)
    end

    def communities
      @communities = Community.paginate(page: params[:page], per_page: 20)
    end
  end
end

app/controllers/community_admin/static_pages_controller.rb
module CommunityAdmin
  class StaticPagesController < ApplicationController
    before_action :authenticate_community!
    before_action :set_community

    def dashboard
      @users = @community.users.paginate(page: params[:page], per_page: 20)
    end

    def users
      @subscribers = @community.subscribers.paginate(page: params[:page], per_page: 20)
    end

    def reports
      @reports_stasuses = [@community.reports.todo, @community.reports.doing, @community.reports.done]
    end

    def location_news
      @deliveries = @community.deliveries
    end

    private

    def set_community
      @community = current_user.community
    end
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def landings_page
  end

end

app/views/community_admin/static_pages/_community_admin_menu.html.erb
<li class='<%= current_page_class(community_admin_dashboard_path) %>'>
  <%= link_to 'Gemeente instellingen', community_admin_dashboard_path %>
</li>
<li class='<%= current_page_class(community_admin_users_path) %>'>
  <%= link_to 'Gemeente abonnees', community_admin_users_path %>
</li>
<li class='<%= current_page_class(community_admin_reports_path) %>'>
  <%= link_to 'Gemeente meldingen', community_admin_reports_path, data: { no_turbolink: true } %>
</li>
<li class='<%= current_page_class(community_admin_location_news_path) %>'>
  <%= link_to 'Melding op locatie', community_admin_location_news_path, data: { no_turbolink: true } %>
</li>

app/views/community_admin/static_pages/dashboard.html.erb
<%= render 'shared/dashboard_menu' %>

<div class='inner'>
  <div class='container'>
    <div class='row'>

      <div class='columns three image-block'>
        <% if @community.avatar? %>
          <%= image_tag @community.avatar_url %>
        <% else %>
          <div class='community_image_name'>
            <%= @community.name %>
          </div>
        <% end %>
      </div>

      <div class='columns nine'>
        <div class='panel'>
          <div class='panel-header'>
            <h5>Gegevens instellingen</h5>
          </div>
          <div class='panel-body'>
            <%= form_for @community do |f| %>
              <div class='row'>
                <div class='columns three'>
                  <%= f.label :avatar, 'Gemeente Logo' %>
                </div>
                <div class='columns nine'>
                  <%= f.file_field :avatar %>
                </div>
              </div>
              <div class='row'>
                <%= f.submit 'Gemeente aanpassen', class: 'button-primary pull-right' %>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>

    <div class='row'>
      <div class='panel'>
        <div class='panel-header'>
          <h5>Gebruikers instellingen <%= link_to 'Gebruiker toevoegen', users_new_community_admin_user_path,
                                                                         remote: true,
                                                                         class: 'js_modal button button-primary
                                                                                 button-sm pull-right' %></h5>
        </div>
        <div class='panel-body'>
          <table class="u-full-width">
            <thead>
              <tr>
                <th>Email</th>
                <th>Categorieen</th>
                <th>Categorie toevoegen</th>
              </tr>
            </thead>
            <tbody>
              <% @users.each do |user| %>
                <tr>
                  <td><%= user.email %></td>
                  <td><%= user.categories.collect(&:title) %></td>
                  <td>
                    <% category_list = Category.all - user.categories %>
                    <% if category_list.any? %>
                      <%= form_for UserCategory.new do |f| %>
                        <%= f.hidden_field :user_id, value: user.id %>
                        <%= f.collection_select :category_id, (category_list), :id, :title,
                                                {include_blank: 'Kies een Categorie'} %>
                        <%= f.submit 'Categorie toevoegen' %>
                      <% end %>
                    <% else %>
                      Alle categorieen toegevoegd
                    <% end %>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
          <%= will_paginate @users %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/community_admin/static_pages/location_news.html.erb
<%= render 'shared/dashboard_menu' %>
<div class='inner'>
  <div class='container'>
    <%= link_to 'Nieuwe melding versturen', new_delivery_path, remote: true, class: 'js_modal' %>

    <table class='u-full-width'>
      <thead>
        <tr>
          <th>Nieuws</th>
          <th>Straten</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <% @deliveries.each do |delivery| %>
          <tr>
            <td>
              <% if delivery.newsletter.present? %>
                <%= delivery.newsletter.title %>
              <% else %>
                <i>Nieuwsbrief verwijderd</i>
              <% end %>
            </td>
            <td>
              <%= delivery.streets %>
            </td>
            <td>
              <% if delivery.delivered? %>
                Verstuurd op <%= delivery.delivered_at %>
              <% else %>
                <%= link_to 'Versturen', deliver_delivery_path(delivery) %>
              <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/community_admin/static_pages/reports.html.erb
<%= render 'shared/dashboard_menu' %>

<div class='inner'>
  <div class='container'>
    <div class='row'>
      <% @reports_stasuses.each_with_index do |report_status, index| %>
        <div class='columns four'>
          <div class='panel'>
            <div class='panel-header'>
              <h5><%= Report.statuses.to_a[index][0] %></h5>
            </div>
            <div class='panel-body'>
              <table class="u-full-width">
                <thead>
                  <tr>
                    <th>Melding</th>
                    <th>Status</th>
                  </tr>
                </thead>
                <tbody>
                  <% report_status.each do |report| %>
                    <tr>
                      <td><%= link_to report.category.title, report, data: { no_turbolink: true }, target: '_blank' %></td>
                      <td>
                        <%= form_for report do |f| %>
                          <%= f.collection_select :status, Report.statuses, :first, :first %>
                        <% end %>
                      </td>
                    </tr>
                  <% end %>
                </tbody>
              </table>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/community_admin/static_pages/users.html.erb
<%= render 'shared/dashboard_menu' %>

<div class='inner'>
  <div class='container'>
    <div class='row'>
      <div class='columns'>
        <div class='panel'>
          <div class='panel-header'>
            <h5>Gebruikers aangemeld bij de gemeente <%= @community.name %></h5>
          </div>
          <div class='panel-body'>
            <table class="u-full-width">
              <thead>
                <tr>
                  <th>Email</th>
                  <th>Rol</th>
                </tr>
              </thead>
              <tbody>
                <% @subscribers.each do |subscriber| %>
                  <tr>
                    <td><%= subscriber.email %></td>
                    <td>
                      <%= subscriber.role_id %>
                    </td>
                  </tr>
                <% end %>
              </tbody>
            </table>
            <%= will_paginate @subscribers %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>