config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  root 'reports#index'

  ### ADMIN ###
  namespace :admin do
    get 'dashboard',    to: 'static_pages#dashboard'
    get 'users',        to: 'static_pages#users'
    get 'communities',  to: 'static_pages#communities'
  end

  ### COMMUNITY_ADMIN ###
  namespace :community_admin do
    get 'dashboard',      to: 'static_pages#dashboard'
    get 'reports',        to: 'static_pages#reports'
    get 'users',          to: 'static_pages#users'
    get 'location_news',  to: 'static_pages#location_news'
  end

  ### COMMUNITIES ###
  resources :communities, only: [:index, :show, :update] do
    get :news, on: :member
    get :community_list, on: :collection
  end

  ### COMMUNITY SUBSCRIPTIONS ###
  resources :community_subscriptions, only: [:create, :destroy] do
    get :delete, on: :member
  end

  ### DELIVERIES ###
  resources :deliveries, only: [:new, :create] do
    get :deliver, on: :member
  end

  ### NEWSLETTERS ###
  resources :newsletters, except: [:edit, :update, :destroy]

  ### REPORTS ###
  resources :reports do
    member do
      get :report_index
      get :info_window
      get :delete
    end
    get :markers, on: :collection
  end

  ### SIDEKIQ ####
  authenticate :user, -> (u) { u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  ### USERS ###
  devise_for :users, controllers: { sessions: 'users/sessions',
                                    registrations: 'users/registrations',
                                    confirmations: 'users/confirmations' }

  resources :users, only: [:index] do
    get :notifications, on: :collection
    get :reports, on: :collection
    get :profile, on: :collection
  end

  post 'users/generate_user', to: 'users#generate_user'
  get 'users/new_admin_user', to: 'users#new_admin_user'
  post 'users/generate_community_admin_user', to: 'users#generate_community_admin_user'
  get 'users/new_community_admin_user', to: 'users#new_community_admin_user'

  ### NOTIFICATIONS ###
  resources :notifications, only: [:destroy]
  post 'notifications/read', to: 'notifications#read'

  ### USER_CATEGORIES ###
  resources :user_categories, only: :create

  ### ZIPCODES ###
  get 'search_streets', to: 'zipcodes#search_streets', as: 'search_streets'
  get 'search_towns', to: 'zipcodes#search_towns', as: 'search_towns'

  ### WRONG WORDS ###
  resources :wrong_words, only: [:index, :create, :destroy]

  ### CATEGORIES ###
  resources :categories, except: [:show]
end

app/models/report.rb
class Report < ActiveRecord::Base
  attr_accessor :community_check_name

  ### CONSTANTS ###
  STATUS_TODO = 0
  STATUS_DOING = 1
  STATUS_DONE = 2

  enum status: {
    open: STATUS_TODO,
    in_behandeling: STATUS_DOING,
    opgelost: STATUS_DONE
  }

  ### UPLOADER ###
  mount_uploader :image_one, ImageUploader
  mount_uploader :image_two, ImageUploader
  mount_uploader :image_three, ImageUploader

  ### GEOCODER ###
  geocoded_by :location
  # after_validation :geocode

  ### ASSOCIATIONS ###
  belongs_to :community
  delegate :name, to: :community, prefix: true
  delegate :email, to: :community, prefix: true
  delegate :phonenumber, to: :community, prefix: true
  belongs_to :user
  has_one :report_category
  accepts_nested_attributes_for :report_category
  has_one :category, through: :report_category

  ### VALIDATIONS ###
  validates :description, presence: true
  validates :address, presence: true
  validates :town, presence: true

  ### SCOPES ###
  scope :todo,  -> { where(status: STATUS_TODO) }
  scope :doing, -> { where(status: STATUS_DOING) }
  scope :done,  -> { where(status: STATUS_DONE) }

  ### CALLBACKS ###
  before_create :set_community, :set_status
  after_create :create_notification
  before_destroy :remove_notifications, :create_destroy_notification
  after_update :check_status_changed_notification
  after_save :check_for_wrong_words

  def set_community
    self.community = Community.find_by(name: community_check_name)
  end

  def set_status
    self.status = STATUS_TODO
  end

  def create_notification
    CreateNotificationJob.perform_later(self) if user.present?
  end

  def check_status_changed_notification
    CreateNotificationStatusChangedJob.perform_later(self, status) if status_changed? && user.present?
  end

  def create_destroy_notification
    CreateDestroyedNotificationJob.perform_later(self) if user.present?
  end

  def remove_notifications
    Notification.where(record_id: id, category_id: 0).each do |notice|
      notice.category_id = Notification::CATEGORY_RECORD_DESTROYED
      notice.save
    end
  end

  def check_for_wrong_words
    CheckForWrongWordsJob.perform_later(self)
  end

  ### INSTANCE METHODS ###
  def location
    address_array = address.split(' ')
    address_array.each do |part|
      address_array.delete(part) if part =~ /\d/
    end
    if address_array.length != 0
      address = address_array.join(' ')
      [address, town].compact.join(', ')
    else
      town
    end
  end

  def location_detail
    [address, town].compact.join(', ')
  end

  def editable_by?(user)
    user == self.user || user.community? && community == user.community || user.admin?
  end

  def image(size)
    if image_one?
      image_one_url(size)
    elsif image_two?
      image_two_url(size)
    elsif image_three?
      image_three_url(size)
    end
  end

  def setting_name_status
    if status == 'open'
      'Open'
    elsif status == 'in_behandeling'
      'In behandeling'
    else
      'Opgelost'
    end
  end
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show, :markers, :report_index, :info_window, :new, :create]
  before_action :set_report, except: [:index, :new, :create, :markers]
  before_action :authenticate_owner, only: [:edit, :update, :destroy]
  before_action :authenticate_community_owner, only: [:edit, :update, :destroy]
  layout false, except: [:index, :show]

  def index
  end

  def show
    render 'show'
  end

  def markers
    if params[:id]
      show_marker
    else
      near_markers
    end
  end

  def show_marker
    render json: Report.find(params[:id]).as_json(include: :category)
  end

  def near_markers
    render json: Report.near([params[:lat], params[:lng]],
                             params[:km], units: :km).as_json(only: [:latitude, :longitude, :id, :status],
                                                              include: :category)
  end

  def report_index
    render partial: 'report', locals: { report: @report }
  end

  def info_window
    render 'info_window'
  end

  def new
    @report = Report.new
    @report_category = ReportCategory.new
  end

  def create
    @report = Report.new(report_params)
    @report.user ||= current_user
    if @report.save
      respond_to do |format|
        format.js
      end
    else
      @report_category = ReportCategory.new
      render partial: 'form', locals: { report: @report, report_category: @report_category }
    end
  end

  def edit
    @report_category = @report.report_category
  end

  def update
    if params[:report][:status] && @report.update(report_params)
      redirect_to community_admin_reports_path, notice: "Status van #{@report.category.title} is aangepast!"
    elsif @report.update(report_params)
      respond_to do |format|
        format.js
      end
    else
      render 'edit'
    end
  end

  def delete
    render 'delete'
  end

  def destroy
    render json: @report if @report.destroy
  end

  private

  def authenticate_owner
    message = 'U bent niet de eigenaar van deze melding!'
    redirect_to root_path, alert: message if current_user.user? && !(@report.user == current_user)
  end

  def authenticate_community_owner
    message = 'U bent geen beheerder van deze gemeente!'
    redirect_to root_path, alert: message if current_user.community? && !(@report.community == current_user.community)
  end

  def set_report
    @report = Report.find(params[:id])
  end

  def report_params
    params.require(:report).permit(:description, :address, :email, :town, :latitude, :status,
                                   :longitude, :resolved_at, :image_one, :image_two, :image_three,
                                   :community_check_name, :has_wrong_word, report_category_attributes: [:category_id])
  end
end

app/views/reports/_form.html.erb
<div class='loading'>
  <div class='spinner'>
    <%= image_tag('spinner.GIF') %>
  </div>
</div>

  <% report.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
  <% end %>

  <div class='icon house'>
    <%= f.text_field :address, placeholder: 'Straat + huisnummer *', class: 'u-full-width js_street_input',
        autocomplete: "off", validate: '' %>
  </div>
  <div class='icon city'>
    <%= f.text_field :town, placeholder: 'Plaatsnaam *', class: 'u-full-width js_town_input',
        autocomplete: "off", validate: '' %>
  </div>

  <%= f.fields_for :report_category, report_category do |rcf| %>
    <%= rcf.collection_select :category_id, Category.all, :id, :title, {include_blank: 'Kies een Categorie'}, validate: '' %>
  <% end %>

  <%= f.text_area :description, placeholder: 'Beschrijving melding *',  class: 'text-field u-full-width', validate: '' %>

  <% if action_name == 'edit' && !(current_user.user?) %>
    <%= f.label :resolved_at, 'Opgelost op' %>
    <%= f.text_field :resolved_at, class: 'u-full-width', class: 'datepicker' %>
  <% end %>

  <% if !user_signed_in? %>
    <div class='icon email'>
      <%= f.label :email, 'Email (blijf op de hoogte)' %>
      <%= f.email_field :email, placeholder: 'Email adres', class: 'u-full-width' %>
    </div>
  <% end %>

  <div class='row'>
    <%= f.label :image_one, 'Afbeeldingen toevoegen (optioneel)' %>
    <%= f.file_field :image_one %>
    <%= f.file_field :image_two %>
    <%= f.file_field :image_three %>
  </div>

  <%= f.hidden_field :latitude, class: 'js_latitude_input' %>
  <%= f.hidden_field :longitude, class: 'js_longitude_input' %>
  <%= f.hidden_field :community_check_name, class: 'js_community_name' %>
  <%= f.hidden_field :has_wrong_word, value: false %>

app/views/reports/_report.html.erb
<div class='clearfix report-show<% if user_signed_in? && report.editable_by?(current_user) && controller_name !=  'users' %> my-report<% end %>' data-report-id='<%= report.id %>'>

  <%= link_to '', report, data: { no_turbolink: true }, class: 'goto-report', target: '_blank'  %>

  <% if report.image(:thumb) != nil %>
    <div class='report-image'>
      <%= image_tag report.image(:thumb), class: 'u-max-full-width' %>
    </div>
  <% end %>
  <div class='report-info clearfix'>
    <span class='date'><%= report.created_at %></span>
    <% if report.image(:thumb) != nil %>
      <h3><%= link_to report.category.title.truncate(16) %></h3>
      <p>
        <% if user_signed_in? && report.editable_by?(current_user) || !(report.has_wrong_word) %>
          <%= report.description.truncate(28) %>
        <% else %>
           Wordt niet getoond...
        <% end %>
      </p>
      <div class='address image'>
        <% if user_signed_in? && report.editable_by?(current_user) %>
          <%= report.location_detail.truncate(32) %>
        <% else %>
          <%= report.location.truncate(32) %>
        <% end %>
      </div>
      <% else %>
      <h3><%= link_to report.category.title.truncate(26) %></h3>
      <p>
        <% if user_signed_in? && report.editable_by?(current_user) || !(report.has_wrong_word) %>
          <%= report.description.truncate(39) %>
        <% else %>
           Wordt niet getoond...
        <% end %>
      </p>
      <div class='address'>
        <% if user_signed_in? && report.editable_by?(current_user) %>
          <%= report.location_detail.truncate(44) %>
        <% else %>
          <%= report.location.truncate(44) %>
        <% end %>
      </div>
    <% end %>

    <% if user_signed_in? %>
      <% if report.editable_by?(current_user) && controller_name !=  'users' %>
        <%= link_to 'Aanpassen', edit_report_path(report), data: {modal_type: 'edit-report', report_id: report.id , remote: true},
            class: 'report-btn fa fa-pencil-square-o js_side_modal' %>
        <%= link_to 'Verwijderen', delete_report_path(report), data: { remote: true,
                                                                modal_type: 'destroy',
                                                                modal_element: 'reports' },
                                                                class: 'report-btn fa fa-trash-o js_side_modal' %>
      <% end %>
    <% end %>
    <div class='status <%= report.status %>'>
      <div class='status-name'><%= report.setting_name_status %></div>
    </div>
  </div>
</div>

app/views/reports/create.js.erb
$('#new_report').on('ajax:success', function() {
  $.ajax({
    type: 'GET',
    dataType: 'json',
    url: '/reports/markers',
    data: { 'id': <%= @report.id %> },
    success: function(data){
      goToReportLocation(data);
      setNotice('Uw melding is ontvangen!');
      removeOldNewMarker();
      removeHeaderModal($('.header-modal'));
    }
  });
});

app/views/reports/delete.html.erb
<div class='side-modal'>
  <div class='modal-content'>
    <div class='close-modal js_close_modal'></div>
    <h5>Melding verwijderen?</h5>
    <div class='clearfix report-modal-show' data-report-id='<%= @report.id %>'>
      <% if @report.image(:thumb) != nil %>
        <div class='report-image'>
          <%= image_tag @report.image(:thumb), class: 'u-max-full-width' %>
        </div>
      <% end %>
      <div class='report-info clearfix'>
        <span class='date'><%= @report.created_at %></span>

        <% if @report.image(:thumb) != nil %>
            <h3><%= @report.category.title.truncate(18) %></h3>
            <p><%= @report.description.truncate(28) %></p>
            <div class='address image'>
              <%= @report.location.truncate(32) %>
            </div>
          <% else %>
            <h3><%= @report.category.title.truncate(26) %></h3>
            <p><%= @report.description.truncate(39) %></p>
            <div class='address'>
              <%= @report.location.truncate(44) %>
            </div>
        <% end %>
      </div>
    </div>
    <div class='delete-wrap'>
      <p class='delete-msg'>Weet u het zeker?</p>
      <%= link_to 'Ja', report_path(@report.id), data: { method: 'delete',
                                                         remote: true,
                                                         id: @report.id,
                                                         controller_name: 'reports' },
                                                         class: 'modal-confirm yes' %>
      <%= link_to 'Nee', '#', class: 'modal-confirm no' %>
    </div>
  </div>
</div>

app/views/reports/edit.html.erb
<div class='side-modal'>
  <div class='modal-content'>
    <div class='close-modal js_close_modal'></div>
    <h5>Melding aanpassen</h5>
    <%= form_for @report, html: { multipart: true, type: :html, class: 'validate' }, remote: true do |f| %>

      <%= render 'form', f: f, report: @report, report_category: @report_category %>
      <%= f.submit 'Melding aanpassen', data: { disable_with: 'Even geduld AUB...' },
                                        class: 'button-primary js_trigger_loading u-full-width' %>
    <% end %>
  </div>
</div>

app/views/reports/index.html.erb
<div class='map-container'>
	<div id='map' class='map'></div>
  <div class='google-maps-search'>
    <input id='pac-input' class='controls search' type='text' placeholder='Zoeken op locatie'>
    <div class='js_current_location current-location'></div>
  </div>
  <div class='js_all_reports all-reports'>

  </div>
  <a href='#' class='reset-map'>Opnieuw laden</a>
  <%= link_to 'Contact', new_message_path, remote: true, class: 'js_header_modal contact-btn',
                                           data: {modal_type: 'contact'} %>
</div>

app/views/reports/info_window.html.erb
<div class='info-box'>
  <div class='close'></div>
  <div class='info'>
    <h3><%= @report.category.title.truncate(32) %></h3>
    <p>
      <% if user_signed_in? && @report.editable_by?(current_user) ||!(@report.has_wrong_word) %>
        <%= @report.description.truncate(100, separator: ' ') %>
      <% else %>
         De beschrijving kan niet worden getoond, vanwege ongepast taal gebruik!
      <% end %>
    </p>
    <div class='address'>
      <% if user_signed_in? && @report.editable_by?(current_user) %>
        <%= @report.location_detail.truncate(120) %>
      <% else %>
        <%= @report.location.truncate(120) %>
      <% end %>
    </div>
  </div>
  <div class='info-footer <%= @report.status %>'>
    <div class="marker <%= @report.status %>">
        <div class="marker-icon <%= @report.category.icon_name %>">
        </div>
    </div>
    <div class='info-link'>
      <%= link_to '', @report, data: { no_turbolink: true }, target: '_blank', class: 'info-arrow' %>
      <%= link_to 'Melding bekijken', @report, data: { no_turbolink: true }, target: '_blank', class: 'link' %>
    </div>
  </div>
</div>

app/views/reports/new.html.erb
<div>
  <div class='arrow-up arrow-report'></div>
  <div class='header-modal report-modal'>
    <div class='close-modal js_close_modal'></div>
    <h5>Melding doen</h5>
    <%= form_for @report, html: { multipart: true, type: :html, class: 'validate' }, remote: true do |f| %>
      <%= render 'form', f: f, report: @report, report_category: @report_category %>
      <%= f.submit 'Melding aanmaken', data: { disable_with: 'Even geduld AUB...' },
                                       class: 'button-primary js_trigger_loading u-full-width' %>
    <% end %>
  </div>
</div>

app/views/reports/show.html.erb
<div id='map' class='map map-show', data-lat='<%= @report.latitude %>', data-lon='<%= @report.longitude %>' ></div>

<% if user_signed_in? %>
  <% if @report.editable_by?(current_user) %>
    <%= link_to 'Aanpassen', edit_report_path(@report), data: {modal_type: 'edit-report',
                                                        report_id: @report.id,
                                                        remote: true},
                                                        class: 'report-show-btn js_side_modal' %>
    <%= link_to 'Verwijderen', delete_report_path(@report), data: { remote: true,
                                                            modal_type: 'destroy',
                                                            modal_element: 'reports' },
                                                            class: 'report-show-btn delete js_side_modal' %>
  <% end %>
<% end %>

<div class='inner details'>
  <div class='container'>
    <div class='row'>
      <div class='columns four'>
        <h1>
          <%= @report.category.title %>
        </h1>
        <% if @report.image(:image_big) != nil %>
          <%= image_tag @report.image(:image_big), class: 'u-max-full-width' %>
        <% end %>
          <div class='address'>
            <% if user_signed_in? && @report.editable_by?(current_user) %>
              <%= @report.location_detail %>
            <% else %>
              <%= @report.location %>
            <% end %>
          </div>
          <p>
            <% if user_signed_in? && @report.editable_by?(current_user) || !(@report.has_wrong_word) %>
              <%= @report.description %>
            <% else %>
               De beschrijving kan niet worden getoond, vanwege ongepast taal gebruik!
            <% end %>
          </p>
      </div>
      <div class='columns eight'>
        <div class='pano'>
          <div id='pano'>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/reports/update.js.erb
$('#edit_report_' + <%= @report.id %>).on('ajax:success', function() {
  if($('.map-show').length) {
    location.reload();
    setAfterReloadNotice('Deze melding is aangepast');
  } else {
    $.ajax({
      type: 'GET',
      dataType: 'json',
      url: '/reports/markers',
      data: { 'id': <%= @report.id %> },
      success: function(data){
        goToReportLocation(data);
        setNotice('Uw melding is aangepast!');
        removeSideModal($('.side-modal'));
        $('.new-marker').remove();
      }
    });
  }
});